### ISSUE TITLE
It is possible to fall into a window.

### ISSUE THREAD

**Issue by aterweele** [anaseto/harmonist#3]
![2020-02-01-155115_1600x624_scrot](https://user-images.githubusercontent.com/17014418/73599749-cabe9d00-453e-11ea-9bed-37b2865c3944.png)

This seems like it should not happen, because I don't think it's normally possible to move into a window.

I was able to move out of the window.

**Comment by anaseto** [comment]
Yeah, it should not happen. It's quite weird, because there's no special code for falling vs descending stairs with respect to player starting position, as far as I remember. I'll need to have a closer look at the code.
