### ISSUE TITLE
Poor Start

### ISSUE THREAD

**Issue by AKubias** [anaseto/harmonist#6]
I started on a chasm but then didn't have a choice to not jump into it. So the game (which is already hard for me) became a lot harder since I missed the first floor and started on floor 2 (without ever actually seeing the first floor).

I saved a replay from the Browser version if needed.

**Comment by anaseto** [comment]
Oh, that should not happen, quite strange indeed, starting position should normally always be inside a vault. I will try to reproduce the issue myself with some automated testing, but the replay might be of help too to get a glance at the specific configuration that triggered that.

Thanks for playing and reporting the issue!

**Comment by AKubias** [comment]
Ok, here is the replay:
https://filebin.net/jqsl885fdl8f4sl1

**Comment by anaseto** [comment]
Thanks for the replay, it helps!

Your game replay starts at turn 212. It seems that somehow all the frames in the first floor have been dropped from the replay. The only explanation I see, is that you thought you started a new game but in fact continued a game automatically saved after a chasm fall, but somehow previous replay data was discarded or already removed (perhaps by the browser). 

Perhaps you started two games at once in different tabs ? Or you closed the tab or browser with a started game (without saving nor quitting properly) and then started a new one on a new tab or after restarting the browser ? This could confuse the saving system and result in loading an automatic save of a previous game at the last floor start (here the second floor) with incomplete replay data.

I've done randomized tests too, and I've not been able to produce any case in which the player was already over chasm. Maybe some kind of additional hint may still be present in “last messages”, in the game statistics. Sadly, the browser version does not offer the option to log all game messages. 

If my intuition about what happened is correct, I'm not sure that it's possible to do anything about it. At most, I could maybe launch a confirmation box before closing a tab with a running game, but I'm not sure this kind of things works equally well with all the browsers.

**Comment by AKubias** [comment]
Ok, thank you. I don't know if that's what happened (it's been a week now so I can't quite remember if I had played before on this computer or not), but it makes sense at least.
